### ISSUE TITLE
issue with parse_deliveries.py file

### ISSUE THREAD

**Issue by ankit2web** [abhijitjaiswal/ipl_stats#2]
_currently parse_deliveries.py file is not producing any csv file._
it is giving errors when interpreted on python shell
_It gives this error_ 

>  Traceback (most recent call last):
>    File "parse_deliveries.py", line 16, in <module>
>      with open("deliveries.csv", 'rb') as d:
>  IOError: [Errno 2] No such file or directory: 'deliveries.csv'

**Comment by abhijitjaiswal** [comment]
You will need to download data from "https://cricsheet.org/downloads/ipl.zip" and unzip into a directory, once unzipped there will be a lot of yaml files. And then you need "parse_innings.py" "parse_info.py" python scripts and specify the unzipped directory path and execute these two scripts only. Each script will generate 2 csv files, then update paths of these two files in "aap.R". Now just Run "app.R" and it will open a up Webpage which will show the output. Hope it helps.

**Comment by ankit2web** [comment]
Closed as the code is working now :+1:
